---
title: "Bayesian Rating Curve"
mathjax: "http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"
output: pdf_document
---
```{r setup, include=FALSE}
Sys.setlocale("LC_ALL","is_IS")
```

```{r echo=FALSE, include=FALSE,warning=FALSE}
library(knitr,quietly=TRUE)
```  
   
      
```{r echo=FALSE,warning=FALSE}
plotlist=model1()
a=exp(plotlist$mu[1,])
b=plotlist$mu[2,]
c_hat=plotlist$c_hat
varappr=mean(plotlist$varappr)
predict=1.96*sqrt(varappr)
```

Formula for rating curve: $$\ \hat{Q}(W) = a \cdot (W - \hat{c})^b = `r a` \cdot (W - `r c_hat` )^{ `r b`}$$
    
Formula for 95 % lower predictive: $$\ \hat{Q}_{lower}(W) = \hat{Q}(W) \cdot {(e^{1.96})}^ {-\sigma_{\epsilon}} = \hat{Q}(W) \cdot {(e^{1.96})}^ {`r -varappr`} = \hat{Q}(W) \cdot `r exp(-predict)`$$

Formula for 95 % upper predictive: $$\ \hat{Q}_{lower}(W) = \hat{Q}(W) \cdot {(e^{1.96})}^ {\sigma_{\epsilon}} = \hat{Q}(W) \cdot {(e^{1.96})}^ {`r varappr`} = \hat{Q}(W) \cdot `r exp(predict)`$$

```{r results='asis',echo=FALSE,warning=FALSE}
plotlist=model1()
tafla=plotlist$tafla
tafla[,"Q fit"]=format(round(tafla[,"Q fit"],3),nsmall=3)
tafla$Lower=format(round(tafla$Lower,3),nsmall=3)
tafla$Upper=format(round(tafla$Upper,3),nsmall=3)
kable(tafla,output=FALSE,caption=paste('Rating Curve from Model 1 for ',input$name))
#stargazer(tafla,type="latex",summary=FALSE, title=paste('Rating Curve from Model 1 for ',input$name),header=FALSE,digits=3,digits.extra=3)
```
   
   
```{r results='asis',echo=FALSE,warning=FALSE}
plotlist=model1()
kable(plotlist$fitrctafla,output=FALSE,caption=paste('Fit for unobserved stages in',input$name))
#stargazer(plotlist$fitrctafla,type="latex",summary=FALSE, title=paste('Fit for unobserved stages in',input$name),header=FALSE,rownames = FALSE)
```

```{r}
```
   
```{r results='asis',echo=FALSE,warning=FALSE}
plotlist=model1()
kable(plotlist$lowerrctafla,output=FALSE,caption=paste('95% posterior predictive lower for unobserved stages in',input$name))
#stargazer(plotlist$lowerrctafla,type="latex",summary=FALSE, title=paste('95% posterior predictive lower for unobserved stages in',input$name),header=FALSE,rownames = FALSE)
```

```{r}
```

```{r results='asis',echo=FALSE,warning=FALSE}
plotlist=model1()
kable(plotlist$upperrctafla,output=FALSE,caption=paste('95% posterior predictive upper for unobserved stages in',input$name))
#stargazer(plotlist$upperrctafla,type="latex",summary=FALSE, title=paste('95% posterior predictive upper for unobserved stages in',input$name),header=FALSE,rownames = FALSE)
```

```{r,echo=FALSE,warning=FALSE}
if(length(plotratingcurve1())!=0)
    if(class(plotratingcurve1()[[1]])[1]=="gg")
        plotratingcurve1()[[1]]
```
   
   
```{r,echo=FALSE,warning=FALSE}
if(length(plotratingcurve1())>=2)
    if(class(plotratingcurve1()[[2]])[1]=="gg")
        plotratingcurve1()[[2]]
```
   
   
```{r,echo=FALSE,warning=FALSE}
if(length(plotratingcurve1())>=3)
    if(class(plotratingcurve1()[[3]])[1]=="gg")
        plotratingcurve1()[[3]]
```
   
   
```{r,echo=FALSE,warning=FALSE}
if(length(plotratingcurve1())>=4)
    if(class(plotratingcurve1()[[4]])[1]=="gg")
        plotratingcurve1()[[4]]
```

```{r results='asis',echo=FALSE,warning=FALSE}
plotlist=model2()
tafla=plotlist$tafla
tafla[,"Q fit"]=format(round(tafla[,"Q fit"],3),nsmall=3)
tafla$Lower=format(round(tafla$Lower,3),nsmall=3)
tafla$Upper=format(round(tafla$Upper,3),nsmall=3)

kable(plotlist$tafla,output=FALSE,caption=paste('Rating Curve from Model 2 for ',input$name))

```

```{r results='asis',echo=FALSE,warning=FALSE}
plotlist=model2()
kable(plotlist$fitrctafla,output=FALSE, caption=paste('Fit for unobserved stages in',input$name))

```

```{r results='asis',echo=FALSE,warning=FALSE}
plotlist=model2()
kable(plotlist$lowerrctafla,output=FALSE,caption=paste('95% posterior predictive lower for unobserved stages in',input$name))

```

```{r results='asis',echo=FALSE,warning=FALSE}
plotlist=model2()
kable(plotlist$upperrctafla,output=FALSE,caption=paste('95% posterior predictive upper for unobserved stages in',input$name),booktabs=FALSE)
#stargazer(plotlist$upperrctafla,type="latex",summary=FALSE, title=paste('95% posterior predictive upper for unobserved stages in',input$name),header=FALSE,rownames = FALSE)
```
```{r,echo=FALSE}
if(length(plotratingcurve2())!=0)
    if(class(plotratingcurve2()[[1]])[1]=="gg")
        plotratingcurve2()[[1]]
```
   
   
```{r,echo=FALSE,warning=FALSE}
if(length(plotratingcurve2())>=2)
    if(class(plotratingcurve2()[[2]])[1]=="gg")
        plotratingcurve2()[[2]]
```
   
   
```{r,echo=FALSE,warning=FALSE}
if(length(plotratingcurve2())>=3)
    if(class(plotratingcurve2()[[3]])[1]=="gg")
        plotratingcurve2()[[3]]
```
   
   
```{r,echo=FALSE,warning=FALSE}
if(length(plotratingcurve2())>=4)
    if(class(plotratingcurve2()[[4]])[1]=="gg")
        plotratingcurve2()[[4]]
```
