---
title: "Bayesian Rating Curve"
mathjax: "http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"
output: pdf_document
---
```{r setup, include=FALSE}
Sys.setlocale("LC_ALL","is_IS")
```

```{r echo=FALSE, include=FALSE,warning=FALSE}
library(knitr,quietly=TRUE)
name=input$name
if(nchar(name)==0){
    name=gsub("\\.[^.]*$","",input$file$name)
}
```  
   
      
```{r echo=FALSE,warning=FALSE}
plotlist1=model1()
a=exp(plotlist1$mu[1,])
b=plotlist1$mu[2,]
c_hat=plotlist1$c_hat
varappr=mean(plotlist1$varappr)
predict=1.96*sqrt(varappr)
```

Formula for rating curve: $$\ \hat{Q}(W) = a \cdot (W - \hat{c})^b = `r a` \cdot (W - `r c_hat` )^{ `r b`}$$
    
Formula for 95 % lower predictive: $$\ \hat{Q}_{lower}(W) = \hat{Q}(W) \cdot {(e^{1.96})}^ {-\sigma_{\epsilon}} = \hat{Q}(W) \cdot {(e^{1.96})}^ {`r -varappr`} = \hat{Q}(W) \cdot `r exp(-predict)`$$

Formula for 95 % upper predictive: $$\ \hat{Q}_{lower}(W) = \hat{Q}(W) \cdot {(e^{1.96})}^ {\sigma_{\epsilon}} = \hat{Q}(W) \cdot {(e^{1.96})}^ {`r varappr`} = \hat{Q}(W) \cdot `r exp(predict)`$$

```{r results='asis',echo=FALSE,warning=FALSE}
plotlist1=model1()
TableOfData=plotlist1$TableOfData
TableOfData[,"Q fit"]=format(TableOfData[,"Q fit"],nsmall=3)
TableOfData$Lower=format(TableOfData$Lower,nsmall=3)
TableOfData$Upper=format(TableOfData$Upper,nsmall=3)
TableOfData[,"Q%"]=format(TableOfData[,"Q%"],nsmall=1)
kable(TableOfData,output=FALSE,caption=paste('Rating curve from Model 1 for ',name))
```
   
   
```{r results='asis',echo=FALSE,warning=FALSE}
kable(plotlist1$FitTable,row.names=FALSE,output=FALSE,caption=paste('Fit from Model 1 in',name))
```
   
```{r results='asis',echo=FALSE,warning=FALSE}
kable(plotlist1$LowerTable,row.names=FALSE,output=FALSE,caption=paste('95% posterior predictive lower from Model 1 in',name))
```

```{r results='asis',echo=FALSE,warning=FALSE}
kable(plotlist1$UpperTable,row.names=FALSE,output=FALSE,caption=paste('95% posterior predictive upper from Model 1 in',name))
```

```{r,echo=FALSE,warning=FALSE}
for(i in 1:length(plotratingcurve1())){
        print(plotratingcurve1()[[i]])
}
```